### PR TITLE
Please Accept I don't take rejection well

### PR DESCRIPTION
**Pull request by wherkamp**
You said "Make the default config sexy" And I added some comments. 
Also I added to the ability to disable the admin warn for outdated plugin.

### CODE REVIEW

**Comment by extendedclip** [comment]
That config isn't even sexy. I wouldn't touch it with a 10 foot @wherkamp penis.

**Comment by wherkamp** [comment]
Ok...

**Comment by Banbeucmas** [comment]
That escalated quickly.
Out of the context, why use Scheduler when you have BukkitScheduler?

**Comment by extendedclip** [comment]
I was just playing. Wanted to see how he would take rejection.

**Comment by extendedclip** [comment]
Damn

**Comment by wherkamp** [comment]
Thanks.......

**Pull request closed without merging**
