### PR TITLE
Add issue template config for custom template selection

### PR DESCRIPTION
**Pull request by Andre601**
[Pull requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls
[contributing file]: https://github.com/PlaceholderAPI/PlaceholderAPI/tree/master/.github/CONTRIBUTING.md

## Please read
Please make sure you checked the following:
- You checked the [Pull requests] page for any upcoming changes.
- You documented any public code that the end-user might use.
- You followed the [contributing file] 

### Type

- [ ] Internal change (Doesn't affect end-user).
- [ ] External change (Does affect end-user).
- [x] Other: New config.yml for issue templates 

This Draft PR adds a `config.yml` to the `.github/ISSUE_TEMPLATE` section, which allows customisation of the template selection, including the addition of external links to sites like wikis, documentation, etc.

I so far implemented the following:
- Disabling option to create blank issues (Can be enabled if requested)
- Adding links to the wiki, paste-site and Discord.

Any additional ideas, links, etc. can be suggested and I'll add them.
If everything is okay, will I make this PR mergable.

Example of new template selection:
image

### CODE REVIEW

**Comment by Funny-cube** [comment]
Maybe change the wiki to be the placeholderapi wiki exclusively, since papi isn't on the main wiki

**Comment by Andre601** [comment]
Done

**Comment by Andre601** [comment]
Is this okay now?
If nothing more is to add/change will I make it mergable.

**Comment by Funny-cube** [comment]
Yeah, looks good

**Pull request merged**
