### PR TITLE
Commands rewrite

### PR DESCRIPTION
**Pull request by Sxtanna**
Please accept my humble offering. ❤️

### CODE REVIEW

**Comment by Sxtanna** [comment]
It's also probably worth noting that while this is primarily a rewrite of the command system, there are also a couple of changes to the internals of the expansion manager and cloud expansion manager.

These changes were to make the plugin more modern and stable.

**Comment by knightzmc** [comment]
my professional opinion is that this is good

**Comment by Sxtanna** [comment]
> my professional opinion is that this is good

I completely agree with this assessment.

**Comment by darbyjack** [comment]
I really love the way this works how it does because of the way it is.

**Comment by Andre601** [comment]
Needs more /daddy xD

**Pull request merged**
