### PR TITLE
OreMarket

### PR DESCRIPTION
**Pull request by OllieJW**
### Type

- [ ] Internal change (Doesn't affect end-user).
- [ ] External change (Does affect end-user).
- [x] Wiki (Changes towards the [Wiki]).
- [ ] Other: __________ 

### Description
Added OreMarket

[Wiki]: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki

### CODE REVIEW

**Comment by Andre601** [comment]
You seem to have trouble adding the placeholders... I'll quickly do it myself to save you some issues.

**Comment by Andre601** [comment]
I'll need the Link to the plugin

**Comment by OllieJW** [comment]
https://www.spigotmc.org/resources/ore-market-stock-market-for-ores-in-minecraft.91015/

**Comment by Andre601** [comment]
[It is done](https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders#oremarket)

Thanks for supporting PlaceholderAPI, even if it was a bit difficult here. :)

**Pull request closed without merging**
