### PR TITLE
Add daddy as a command alias

### PR DESCRIPTION
**Pull request by extendedclip**
[Pull requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls
[contributing file]: https://github.com/PlaceholderAPI/PlaceholderAPI/tree/master/.github/CONTRIBUTING.md

## Please read
Please make sure you checked the following:
- You checked the [Pull requests] page for any upcoming changes.
- You documented any public code that the end-user might use.
- You followed the [contributing file] 

### Type

- [x] Internal change (Doesn't affect end-user).
- [ ] External change (Does affect end-user).
- [ ] Other: __________ 

Do not delete this PR. Lets talk about it. I want to know why its so bad... I personally like the alias and would use it over /papi any day.

### CODE REVIEW

**Comment by PiggyPiglet** [comment]
So long it's behind a permission like @Sxtanna said, there's no reason this can't be added back.

**Comment by LemmoTresto** [comment]
I'm all for having the alias, afaik it was only removed due to someone complaining. So I'd agree of having it behind a permission.

**Comment by extendedclip** [comment]
The problem is /daddy will still return the no permission message.

**Comment by BomBardyGamer** [comment]
This should've been PR'd just for the memes lol

**Pull request closed without merging**
