### PR TITLE
Added permissions to base command and help command

### PR DESCRIPTION
**Pull request by TheBlueKingLP**
[Pull requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls
[contributing file]: https://github.com/PlaceholderAPI/PlaceholderAPI/tree/master/.github/CONTRIBUTING.md

## Please read
Please make sure you checked the following:
- You checked the [Pull requests] page for any upcoming changes.
- You documented any public code that the end-user might use.
- You followed the [contributing file] 

### Type

- [ ] Internal change (Doesn't affect end-user).
- [x] External change (Does affect end-user).
- [ ] Other: __________ 

Added permission "placeholderapi.help" to both the base command(`/placeholderapi`) and the help command(`/placeholderapi help`) and in the plugins.yml so normal players will not see the placeholderapi command in the command suggestion list

### CODE REVIEW

**Comment by Andre601** [comment]
I don't see why this is needed here.
Literally no one so far has ever complained that they don't like people to access `/papi` and `/papi help`

**Comment by TheBlueKingLP** [comment]
The reason for adding the permission is to unclutter the command tab completer and the auto generated help command, once a permission is added, those command will be removed from those areas of a player who don’t have permission to use those commands.

**Comment by Andre601** [comment]
@TheBlueKingLP PlaceholderAPI has received some major changes in its command system and also the plugin.yml, so you should try to update your PR for this,

**Comment by Andre601** [comment]
@TheBlueKingLP Are you still working on this? We would like to merge this, but the conflics listed below make this not possible.
It would be appreciated if you could update the PR.

Thank you.

**Comment by extendedclip** [comment]
I am closing this. If you wish to add this feature please update and re open or submit a new pr

**Pull request closed without merging**
