### PR TITLE
Google Codestyle

### PR DESCRIPTION
**Pull request by Sxtanna**
This PR establishes a plugin enforced codestyle.

### CODE REVIEW

**Comment by Sxtanna** [comment]
*disclaimer*
This plugin requires Gradle to run with Java 11. _(this does not mean that placeholderapi will require Java 11 to function.)_

**Comment by Sxtanna** [comment]
I was originally ok with this because it's what @extendedclip wants, but honestly, this style is kinda trash.

The collapsing of elements really hurts readability.

**Comment by Andre601** [comment]
It's his project after all, so I think we should at least give him the freedom of how he wants his project to look in terms of code style.

**Comment by Sxtanna** [comment]
> It's his project after all, so I think we should at least give him the freedom of how he wants his project to look in terms of code style.

Except the style is completely unreadable.

**Comment by Andre601** [comment]
Can we just go with it please?
Unreadable or not, your opinion here is only one of many and clip's opinion is more important here.

**Comment by Sxtanna** [comment]
> Unreadable or not

You have almost no actual programming contribution to this repo, readability has very little importance to you. 

The source is meant to be read and understood by humans, the compiler couldn't care less how it looks. There is no benefit to not being able to read the damn code.

Nothing to gain, everything to lose.

**Comment by Andre601** [comment]
You should first fix your *"IDE"* making the code look shit before telling me it has "very little importance for me".

image

The google codestyle isn't any less readable for a human than whatever you want to use.
And I did do my fair share of contributions to this project and using PlaceholderAPI in several plugins and expansions, so I believe it does have importance to me to a certain extend.

**Comment by Sxtanna** [comment]
> You should first fix your "IDE" making the code look shit

1. Why is IDE in quotes?
2. It is not IntelliJ that does that, it's github/chrome.
Either GitHub or Chrome is rendering tabs as 8 spaces instead of the more normal 4.

You can see this by appending the tab modifier parameter to the URL of the file:
https://github.com/PlaceholderAPI/PlaceholderAPI/blob/master/src/main/java/me/clip/placeholderapi/commands/PlaceholderCommandRouter.java?ts=4

Tabs are the better spacer as they allow individuals to customize how they want their code to look, without modifying the code for everyone.

> The google codestyle isn't any less readable for a human than whatever you want to use.

What I "want" to use is not entirely mutually exclusive of google's code style.
I am using the "Allman" brace indentation format. It is not a codestyle on its own, just a way to indent braces.

Please take the time to actually read through the way the code is formatted in this branch, it's a fucking mess, and it's completely unreadable.

> And I did do my fair share of contributions to this project

This is just objectively untrue, sorry.

**Comment by Andre601** [comment]
I'm sorry that I didn't had 200 commits to this project, but I did do commits and helped more than once here (The issue templates where mostly made by me f.e.).

All I say is, that you don't need to have many contributions here to have a voice and give your own feedback here. The commit count isn't relevant here.
People will mostly care for Javadocs anyway, so why bother that the indend/position of a { is like 2 spaces of or something?

**Comment by Andre601** [comment]
Also, if this bothers you so much, why keep this PR open? Why not just close it then? You opened it after all, so if this annoys you so much and you want to enforce your way of codestyle, why not do so then?

**Comment by Sxtanna** [comment]
> All I say is, that you don't need to have many contributions here to have a voice and give your own feedback here. The commit count isn't relevant here.

This is legit not at all what I said, I never implied you have no contributions. I said, and I quote, **"You have almost no actual programming contribution to this repo, readability has very little importance to you."**

Which is objectively true, 80% of your contributions have been to documentation, the wiki, and github issue/contribution/pull request files.

When you say to do something whether it is readable or not, you are showing that readability does not matter to you.

Unfortunately, readability is of the utmost importance to me, or anyone else you needs to actually like.... read the code.

I'm going to be locking this, and having a discussion with clip about where to go further.

**Pull request closed without merging**
