### PR TITLE
Add api-version: 1.13 to plugin.yml

### PR DESCRIPTION
**Pull request by Leomixer17**
[Pull requests]: https://github.com/PlaceholderAPI/PlaceholderAPI/pulls
[contributing file]: https://github.com/PlaceholderAPI/PlaceholderAPI/tree/master/.github/CONTRIBUTING.md

## Please read
Please make sure you checked the following:
- You checked the [Pull requests] page for any upcoming changes.
- You documented any public code that the end-user might use.
- You followed the [contributing file] 

### Type

- [x] Internal change (Doesn't affect end-user).
- [ ] External change (Does affect end-user).
- [ ] Other: __________

### CODE REVIEW

**Comment by GMatrixGames** [comment]
Has this been tested in all versions PAPI supports? Last I checked Clip committed this, then reverted it

**Comment by darbyjack** [comment]
Correct, we reverted it because it caused some issues.

**Comment by Leomixer17** [comment]
@GMatrixGames It doesn't causes any issue

**Comment by Andre601** [comment]
I don't think this would cause issues on 1.13 and 1.14.
1.12 doesn't have this api-check which means it wouldn't affect 1.12 and older.

**Comment by ChineseMarc** [comment]
api-version 1.14 can cause issues on 1.13

**Comment by Leomixer17** [comment]
@ChineseMarc It's 1.13, not 1.14

**Pull request merged**
